#!/bin/sh

### BEGIN INIT INFO
# Provides:          autoboot for rubikcube solver
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start rubik cube solver
# Description:       start rubik cube solver
### END INIT INFO
export NODE_PATH=/home/pi/RubikCubeSolver/node_modules 
case $1 in
        start)
               forever /home/pi/RubikCubeSolver/server_offline.js start
                ;;
        stop)
               forever /home/pi/RubikCubeSolver/server_offline.js stop
				;;
        *)
                echo "Usage: $0 (start|stop)"
                ;;
esac
exit 0

